namespace HDStation
{
    using System;
    
    public partial class INFORTAPE
    {
        public long ID_CLIP { get; set; }
        public string MA_BANG { get; set; }
        public string TC_IN { get; set; }
        public string TC_OUT { get; set; }
        public string TL { get; set; }
        public int IS_SERVER { get; set; }
        public int IS_VTR { get; set; }
        public int? IS_NAS { get; set; }
        public int PLAYTIME { get; set; }
        public string REAL_TC_IN { get; set; }
        public string REAL_TC_OUT { get; set; }
        public int? TYPE { get; set; }
        public int NAS_ID_EDIT { get; set; }
        public int SECTION { get; set; }
        public string TEN_CHUONG_TRINH { get; set; }
        public string NOI_DUNG { get; set; }
        public DateTime? CREATE_DATE { get; set; }
        public DateTime? RECORD_DATE { get; set; }
        public int? TIME_TO_LIVE { get; set; }
        public int? APPROVED { get; set; }
        public string COMMENT { get; set; }
        public int? USERID { get; set; }
        public int? SOURCE { get; set; }
        public int? IS_RAW { get; set; }
        public int? NAS_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string HD_CLIP { get; set; }
        public int? AFD_TYPE { get; set; }
        public string TEMPORARY_FILE_NAME { get; set; }
        public int? SERVICE_LOW_RES_STATUS { get; set; }
        public int? SERVICE_VOICE_OVER_STATUS { get; set; }
        public int? SERVICE_SUBTITLE_STATUS { get; set; }
        public int? SERVICE_REQUEST { get; set; }
        public int? RTB_CHECKING { get; set; }
        public int? NAS_ID_PREVIEW { get; set; }
        public int? NAS_ID_TEMPORARY { get; set; }
        public int? SERVICE_PRIORITY { get; set; }
        public string VERSION { get; set; }
        public string VIDEO_FORMAT { get; set; }
        public string TITLE_ORIGIN { get; set; }
        public DateTime? START_RIGHTS { get; set; }
        public DateTime? END_RIGHTS { get; set; }
        public string RUNS { get; set; }
        public string NOTE { get; set; }
        public long? LTO_ID { get; set; }
        public DateTime? LAST_ACCESSED_TIME { get; set; }
        public double? AUDIO_LEVEL { get; set; }
        public int? RAW_CHECK { get; set; }
        public string RAW_CHECK_NOTE { get; set; }
        public int? USER_ID_RAW_CHECK { get; set; }
        public int? USER_ID_DECIDE_SERVICE { get; set; }
        public int? POST_QUALITY_CHECK { get; set; }
        public string POST_QUALITY_CHECK_NOTE { get; set; }
        public int? USER_ID_POST_QUALITY_CHECK { get; set; }
        public int? POST_CONTENT_VTV_CHECK { get; set; }
        public string POST_CONTENT_VTV_CHECK_NOTE { get; set; }
        public int? USER_ID_POST_CONTENT_VTV_CHECK { get; set; }
        public int? POST_CONTENT_VSTV_CHECK { get; set; }
        public string POST_CONTENT_VSTV_CHECK_NOTE { get; set; }
        public int? USER_ID_POST_CONTENT_VSTV_CHECK { get; set; }
        public string KEYWORDS { get; set; }
        public int? ORIGINAL_SERVICE_REQUEST { get; set; }
        public int? USER_ID_RTB_CHECKING { get; set; }
        public int? CAN_COPY { get; set; }
        public int? CLIP_SOURCE_TYPE { get; set; }
        public string VERSION_FILE_DATE { get; set; }
        public string REASONABLE_SCENCES { get; set; }
        public string ASPECT_RATIO { get; set; }
        public string CODEC { get; set; }
        public int? APPROVER_USER_ID { get; set; }
        public string APPROVER_COMMENT { get; set; }
        public int? MASTER_CLIP_ID { get; set; }
        public int? EPISODE_NUMBER { get; set; }
        public bool ALLOW_ARCHIVING { get; set; }
        public int? POST_CHECK_SX { get; set; }
        public string POST_CHECK_SX_NOTE { get; set; }
        public int? USER_ID_POST_CHECK_SX { get; set; }
        public long? FILE_SIZE { get; set; }
        public string CODE { get; set; }
        public string THUMB_FRAME { get; set; }
        public int? THUMB_CREAT_STATUS { get; set; }
        public string THUMB_FILE_NAME { get; set; }
        public DateTime? SERVICE_LOW_RES_LAST_UPDATE { get; set; }
        public string TRANSCODING_ID { get; set; }
        public DateTime? EXPIRATION_DATE { get; set; }
        public long? IDPS { get; set; }
        public int? Changed { get; set; }
        public int? FILE_TRANS_STATUS { get; set; }
        public string RTB_CHECK_NOTE { get; set; }
        public int? PROJECT_ID { get; set; }
        public int? WORKFLOW_ID { get; set; }
        public int? WORKFLOW_TYPE { get; set; }
        public long? WORKFLOW_POST_ID { get; set; }
        public string LOGS { get; set; }
        public int? SERVICE_TRANSCODE_STATUS { get; set; }
        public int? NAS_ID_TKC { get; set; }
        public int? ISSERVER_TKC { get; set; }
        public int? SAFETY_POLICY { get; set; }
        public DateTime? DATE_TO_BROADCAST { get; set; }
        public int? SERVICE_EXPORT_STATUS { get; set; }
        public string EXPORT_FILE_NAME { get; set; }
        public int? SERVICE_QC_STATUS { get; set; }
        public string SERVICE_QC_NOTE { get; set; }
        public long? NEWS_ID { get; set; }
        public int? SERVICE_TC_STATUS { get; set; }
        public string HIGH_RES_CHECKSUM { get; set; }
        public string APPROVE_HR_CHECKSUM { get; set; }
        public string MEDIA_INFOR_JSON { get; set; }
        public long? WORKFLOW_INSTANCE_ID { get; set; }
        public long? PP_PROJECT_ID { get; set; }
        public DateTime? SYNC_CLIP_LAST_TIME { get; set; }
        public int? SERVICE_VERIFICATION_UPDATE_REQUEST { get; set; }
        public long? SOURCE_MEDIA_ID { get; set; }
        public int? LTO_COPIES { get; set; }
        public int? LTO_COPIES_REQUEST { get; set; }
        public int? LTO_RESTORE_REQUEST { get; set; }
        public int? LTO_ARCHIVE_REQUEST { get; set; }
        public int? SERVICE_TRANSCODE_VOD { get; set; }
        public DateTime? SERVICE_TRANSCODE_VOD_LAST_UPDATE { get; set; }
        public int? SERVICE_TRANSCODE_OTT { get; set; }
        public DateTime? SERVICE_TRANSCODE_OTT_LAST_UPDATE { get; set; }
        public int? SCENE_DETECT_REQUEST { get; set; }
        public DateTime? SCENE_DETECT_LAST_UPDATE { get; set; }
        public int? LOUNDNESS_REQUEST { get; set; }
        public DateTime? LOUNDNESS_LAST_UPDATE { get; set; }
        public int? SERVICE_TRANSCODE_PLAYOUT { get; set; }
        public DateTime? SERVICE_TRANSCODE_PLAYOUT_LAST_UPDATE { get; set; }
        public string Loudness { get; set; }
        public int? EXTERNAL_REQUEST_UPLOAD_STATUS { get; set; }
        public string EXTERNAL_REQUEST_UPLOAD_FILE_NAME { get; set; }
        public string EXTERNAL_CENSORSHIP_STATUS { get; set; }
        public string EXTERNAL_STORAGE_STATUS { get; set; }
        public int? SERVICE_VERIFICATION_STATUS { get; set; }
        public string SERVICE_VERIFICATION_REPORT { get; set; }
        public bool IS_REMOVED { get; set; }
        public string EXTERNAL_CODE { get; set; }
        public bool? EtereAssetChanged { get; set; }
        public bool? EtereAssetEdlChanged { get; set; }
        public bool? EtereAssetFlexiMetadataChanged { get; set; }
        public bool? EtereMediaDeleted { get; set; }
        public string EXTERNAL_QC_STATUS { get; set; }
        public bool? COPYRIGHT { get; set; }
        public DateTime? COPYRIGHT_START { get; set; }
        public DateTime? COPYRIGHT_END { get; set; }
        public string CommingNextNow { get; set; }
        public string Season { get; set; }
        public string Director { get; set; }
        public string Actor { get; set; }
        public int? ReleasesYear { get; set; }
        public DateTime? EXTERNAL_UPLOAD_START_TIME { get; set; }
        public int? PCD_REQUEST_UPLOAD_STATUS { get; set; }
        public string PCD_REQUEST_UPLOAD_FILE_NAME { get; set; }
        public bool? VTVPCDChanged { get; set; }
    }
}